version: '3'
services:
  redis1:
    image: redis
    command: redis-server /usr/local/etc/redis/redis1.conf
    volumes: 
      - ./:/usr/local/etc/redis
    ports: 
      - "6379:6379"

  redis2:
    image: redis
    command: redis-server /usr/local/etc/redis/redis2.conf
    volumes:
      - ./:/usr/local/etc/redis    
    ports: 
      - "6380:6380"
    links: 
      - redis1:redis1
